feature(WORK-5126): Create Jira Issue for Dependency Alerts JOB

diff --git a/.github/workflows/dependency-alerts.yml b/.github/workflows/dependency-alerts.yml
--- a/.github/workflows/dependency-alerts.yml
+++ b/.github/workflows/dependency-alerts.yml
@@ -6,7 +6,7 @@ on:
 
 env:
   PARENT_KEY: WORK-5159
-  PROJECT_ID: 13243
+  PROJECT_KEY: WORK
   JIRA_EMAIL: luis.meneses@varsitytutors.com
   JIRA_API_TOKEN: ATATT3xFfGF0_neZld5pUL5SsjQAmCqBzu-UzGh-1JZYRB691CaJ-W6WyMgVQXGpoAZ8rm4_HYXZ0Xz_ZXO5KYh-FkR902e-VdvVszdIS3CfgUhxCDyFH1OjiVrouac87AovcWojuXdtNif_w4_2txLTg4mn55nUI0x2U-lL_99ekW1yPVYfsZE=B1455881
 
@@ -22,7 +22,7 @@ jobs:
 
       - name: Create Jira Issue
         run: |
-          curl --verbose --request POST \
+          response=$(curl --verbose --request POST \
           --url 'https://varsity.atlassian.net/rest/api/2/issue' \
           --user '${{ env.JIRA_EMAIL }}:${{ env.JIRA_API_TOKEN }}' \
           --header 'Accept: application/json' \
@@ -38,7 +38,12 @@ jobs:
                   "key": "${{ env.PARENT_KEY }}"
               },
               "project": {
-                  "key": "WORK"
+                  "key": "${{ env.PROJECT_KEY }}"
               }
             }
-          }'
+          }')
+
+          if [ "$response" -ne 201 ]; then
+          echo "Request failed with status $response"
+          exit 1
+          fi
